# Generated by Django 5.1.4 on 2025-01-10 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0002_blogcategorymodel_alter_bloghashgtagmodel_created_at_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='blogcommentmodel',
            options={'verbose_name': 'comment', 'verbose_name_plural': 'comments'},
        ),
        migrations.AlterModelOptions(
            name='bloglikesmodel',
            options={'verbose_name': 'like', 'verbose_name_plural': 'likes'},
        ),
        migrations.AddField(
            model_name='blogcommentmodel',
            name='comment',
            field=models.TextField(default='Default comment'),
        ),
    ]
