# Generated by Django 5.1.4 on 2025-01-08 14:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='blogshopmodel',
            options={'ordering': ['name'], 'verbose_name': 'BlogShop', 'verbose_name_plural': 'BlogShops'},
        ),
    ]
