# Generated by Django 5.1.4 on 2025-01-18 04:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_productcategorymodel_productimagemodel_productmodel_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='productmodel',
            name='categories',
            field=models.ManyToManyField(related_name='products', to='shop.productcategorymodel'),
        ),
    ]
